name: flutter_application_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  avatar_glow: ^2.0.2
  speech_to_text: ^6.3.0
  flutter_tts: ^3.0.0
  http: ^0.13.6
  dio: ^5.3.2
  flutter_secure_storage: ^8.0.0
  flutter_unity_widget: ^2022.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Klee_One
      fonts:
        - asset: assets/fonts/Klee_One/KleeOne-Regular.ttf
          weight: 100
        - asset: assets/fonts/Klee_One/KleeOne-SemiBold.ttf
          weight: 100
  uses-material-design: true
